modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL="${mod_homepage}/issues"

[[mods]]
modId = "${mod_id}"
version = "${file.jarVersion}"
displayName = "${mod_name}"
displayURL="${mod_homepage}"
logoFile = "icon.png"
authors = "Jamalam"
description = '''
${mod_description}
'''

[[dependencies.${mod_id}]] #optional
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "BOTH"
